Bootstrap: docker
From: ghcr.io/astral-sh/uv@sha256:1cc0392c8aad8026ef3922e3f997fff0f31e506b0ffe951afde2ba12728911b8

# Refer to Dockerfile for comments about build process. Apptainer does not
# support layer caching which results in a much less interesting build file.

%environment
    export PATH="/vEcoli/.venv/bin:$PATH"
    export IMAGE_GIT_HASH="{{ git_hash }}"
    export IMAGE_GIT_BRANCH="{{ git_branch }}"
    export IMAGE_TIMESTAMP="{{ timestamp }}"
    export UV_CACHE_DIR="/vEcoli/.uv_cache"
    # runscripts/container/build-image.sh has some custom logic to replace this
    # with the environment variables that are set in .env
    {{ dot_env_vars }}

%labels
    application "Whole Cell Model Runtime Environment"
    email "wholecellteam@lists.stanford.edu"
    license "https://github.com/CovertLab/vEcoli/blob/master/LICENSE"
    organization "Covert Lab at Stanford"
    website "https://www.covert.stanford.edu/"

%files
    repo.tar /repo.tar

%post
    mkdir -p /vEcoli
    if [ -f /repo.tar ]; then
        tar -xf /repo.tar -C /vEcoli
        rm /repo.tar
    fi
    apt-get update && apt-get install -y gcc procps nano curl
    cd /vEcoli
    UV_CACHE_DIR="/vEcoli/.uv_cache" UV_COMPILE_BYTECODE=1 uv sync --frozen
