version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    rebase-strategy: "auto"
    commit-message:
      prefix: "chore(deps): update"
    labels:
    - "dependencies"
