[pytest]
python_files = *.py
addopts = --doctest-modules --strict-markers --ignore=wholecell/utils/_netflow --assert=plain
testpaths =
    ecoli
    runscripts
    wholecell
    reconstruction
markers =
    slow: indicates slow tests (deselect with '-m "not slow"')
    noci: indicates tests that should not run on CI (e.g. because they are too slow)
    master: indicates tests that should only run on master
    basic_workflow: selects a subset of 'MockEcoliSimWorkflow' tests for development
tmp_path_retention_policy = failed
tmp_path_retention_count = 1
filterwarnings =
    ignore::DeprecationWarning:multiprocessing.popen_fork
    ignore::DeprecationWarning:vivarium.core.composition
