import os
import numpy as np
import matplotlib.pyplot as plt

from typing import Any, TYPE_CHECKING
from ecoli.library.parquet_emitter import (
    read_stacked_columns,
    field_metadata,
    named_idx,
)

if TYPE_CHECKING:
    from duckdb import DuckDBPyConnection


def plot(
    params: dict[str, Any],
    conn: "DuckDBPyConnection",
    history_sql: str,
    config_sql: str,
    success_sql: str,
    sim_data_paths: dict[str, dict[int, str]],
    validation_data_paths: list[str],
    outdir: str,
    variant_metadata: dict[str, dict[int, Any]],
    variant_names: dict[str, str],
):
    """
    Args:
        params: Dictionary of parameters given under analysis
            name in configuration JSON.
        conn: DuckDB database connection, automatically created
            by runscripts/analysis.py with appropriate settings.
        history_sql: DuckDB SQL query that filters simulation
            output data to subset appropriate for analysis type
            (e.g. single cell for ``single`` analyses).
        config_sql: DuckDB SQL query that filters simulation
            config data to subset appropriate for analyis type.
        success_sql: DuckDB SQL query to Hive-partitioned
            Parquet dataset which only contains successful sims.
        sim_data_paths: Mapping from experiment IDs to mapping
            from variant indices to variant simulation data
            pickle paths. Generated by runscripts/analysis.py
            either using:

                - Combination of  ``sim_data_path``, ``variant``,
                  ``variant_metadata_path``, and ``experiment_id``
                  configuration options
                - Traversing directories in ``variant_data_dir`` and
                  matching discovered variants with experiment IDs
                  given in ``experiment_id`` (preferred route for
                  most use cases)

        validation_data_paths: List of validation data pickle
            paths taken directly from ``validation_data_path``
            configuration option.
        outdir: String path equal to ``outdir`` configuration option
            prepended to Hive partitioned directory representing data
            filters applied to ``history_sql``. For example, a ``single``
            analysis script run on data for experiment ID "test",
            variant index 1, lineage seed 3, generation 2, and agent ID
            "00" will get: ``{outdir}/experiment_id=test/variant=1/
            lineage_seed=3/generation=2/agent_id=00``. By convention,
            analysis scripts should save their outputs in this folder.
        variant_metadata: Mapping from experiment IDs to mapping
            from variant indices to parameters used to create variant
            simulation data object. Generated by runscripts/analysis.py
            in one of the same two methods used for sim_data_paths.
        variant_names: Mapping from experiment IDs to name of variant
            function used to generate variant simulation data objects
            for workflow run. Generated by runscripts/analysis.py
            in one of the same two methods used for sim_data_paths.
    """

    # Set up subplots according to parameters
    n_subplots = len(params["plot_reactions"])
    fig, axs = plt.subplots(n_subplots, 1)

    # Retrieve reaction IDs from config metadata
    reaction_ids = np.array(
        field_metadata(conn, config_sql, "listeners__fba_results__base_reaction_fluxes")
    )

    # Plot each reaction set in a separate axis
    for reaction_set, ax in zip(params["plot_reactions"], axs):
        if isinstance(reaction_set, str):
            reaction_set = {reaction_set: reaction_set}
        elif isinstance(reaction_set, list):
            reaction_set = dict(zip(reaction_set, reaction_set))

        # Complain if any reaction ids don't exist in the data
        for rxnid in reaction_set.keys():
            if rxnid not in reaction_ids:
                raise KeyError(
                    f"Reaction with ID {rxnid} was not found in the set of metabolic reactions!"
                )

        # Get reactions indices and read flux values
        reaction_idx = list(
            np.where(np.isin(reaction_ids, list(reaction_set.keys())))[0]
        )
        flux_data = read_stacked_columns(
            history_sql,
            [
                named_idx(
                    "listeners__fba_results__base_reaction_fluxes",
                    list(reaction_set.keys()),
                    [reaction_idx],
                )
            ],
            conn=conn,
        )

        # Plot flux traces
        for reaction_id, label in reaction_set.items():
            ax.plot(flux_data["time"], flux_data[reaction_id], label=label)

        # Axis aesthetics
        ax.set_xlabel("Time")
        ax.set_ylabel("Flux")
        ax.legend()

    fig.set_size_inches(8, len(axs) * 4)
    fig.tight_layout()

    fig.savefig(os.path.join(outdir, "selected_fluxes.svg"))
    fig.savefig(os.path.join(outdir, "selected_fluxes.png"))
