Bootstrap: docker
From: ghcr.io/astral-sh/uv@sha256:21051ff1d154bb559756e842d8b49f6e1f12cbbf75895b818df6e5c4ab50a2e7

%environment
    export PATH="/vEcoli/.venv/bin:$PATH"
    export UV_PROJECT_ENVIRONMENT="/vEcoli/.venv"

%labels
    application "Whole Cell Model Runtime Environment"
    email "wholecellteam@lists.stanford.edu"
    license "https://github.com/CovertLab/vEcoli/blob/master/LICENSE"
    organization "Covert Lab at Stanford"
    website "https://www.covert.stanford.edu/"

%files
    uv.lock /vEcoli/uv.lock
    pyproject.toml /vEcoli/pyproject.toml
    .env /vEcoli/.env

%post
    echo "Setting up runtime environment..."

    echo "alias ls='ls --color=auto'" >> ~/.bashrc
    echo "alias ll='ls -l'" >> ~/.bashrc
    cp ~/.bashrc /

    apt-get update && apt-get install -y git gcc procps

    # Variables defined in %environment are not available in %post
    # so we set UV_COMPILE_BYTECODE here to ensure bytecode is compiled
    UV_COMPILE_BYTECODE=1 uv sync --frozen --no-install-project --no-dev --project vEcoli

%runscript
    # Source the .env file before starting shell.
    if [ -f /vEcoli/.env ]; then
        echo "Loading environment variables from /vEcoli/.env"
        set -a
        source /vEcoli/.env
        set +a
    fi
    exec /bin/bash
