Bootstrap: docker
From: ghcr.io/astral-sh/uv@sha256:9e963fcd233dcc215cb0b6899a95a5f8c5cf9f51f3b3575f48a4ae4c1e4efadd

%environment
    export OPENBLAS_NUM_THREADS=1

%labels
    application "Whole Cell Model Runtime Environment"
    email "allencentercovertlab@gmail.com"
    license "https://github.com/CovertLab/vEcoli/blob/master/LICENSE"
    organization "Covert Lab at Stanford"
    website "https://www.covert.stanford.edu/"

%files
    uv.lock /vEcoli/uv.lock
    pyproject.toml /vEcoli/pyproject.toml

%post
    echo "Setting up runtime environment..."

    echo "alias ls='ls --color=auto'" >> ~/.bashrc
    echo "alias ll='ls -l'" >> ~/.bashrc
    cp ~/.bashrc /

    apt-get update && apt-get install -y git gcc

    USE_CYTHON=1 CC=gcc uv sync --frozen --no-install-project --no-dev --project vEcoli

%runscript
    # This defines the default behavior when the container is executed.
    exec /bin/bash
