Bootstrap: localimage
From: {{ from }}

%labels
    application "Whole Cell Model of Escherichia coli"
    email "wholecellteam@lists.stanford.edu"
    license "https://github.com/CovertLab/vEcoli/blob/master/LICENSE"
    organization "Covert Lab at Stanford"
    website "https://www.covert.stanford.edu/"

%environment
    # Record Image metadata in ENV variables, accessible to programs in the container
    export IMAGE_GIT_HASH="{{ git_hash }}"
    export IMAGE_GIT_BRANCH="{{ git_branch }}"
    export IMAGE_TIMESTAMP="{{ timestamp }}"

%files
    FILES_TO_ADD

%post
    # Set the working directory
    cd /vEcoli
    
    # Install dependencies using uv
    uv sync --frozen
    
    # Since this build runs as root, set permissions so running the container as
    # another user will work: Parca writes into /vEcoli/cache/.
    umask 000 && mkdir -p /vEcoli/cache

%runscript
    # Source the .env file before starting shell.
    if [ -f /vEcoli/.env ]; then
        echo "Loading environment variables from /vEcoli/.env"
        set -a
        source /vEcoli/.env
        set +a
    fi
    exec /bin/bash "$@"
