Bootstrap: localimage
From: {{ runtime_image }}

%labels
    application "Whole Cell Model of Escherichia coli"
    email "allencentercovertlab@gmail.com"
    license "https://github.com/CovertLab/vEcoli/blob/master/LICENSE"
    organization "Covert Lab at Stanford"
    website "https://www.covert.stanford.edu/"

%environment
    export IMAGE_GIT_HASH="{{ git_hash }}"
    export IMAGE_GIT_BRANCH="{{ git_branch }}"
    export IMAGE_TIMESTAMP="{{ timestamp }}"
    export PYTHONPATH="/vEcoli"

%files
    . /vEcoli

%post
    echo "Setting up vEcoli environment..."
    cd /vEcoli
    make clean compile

%runscript
    exec /bin/bash
