name: Docker Build and Security Scan

permissions:
  contents: read
  security-events: write
  actions: read

on:
  push:
    branches:
      - master
  pull_request:
  merge_group:
    branches: [master]
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.merge_group.head_sha || github.ref }}
  cancel-in-progress: true

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: runscripts/container/Dockerfile
          load: true
          tags: vecoli:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Scan image with Trivy (SARIF)
        if: github.event_name != 'pull_request'
        id: trivy-sarif
        uses: aquasecurity/trivy-action@0.34.2
        with:
          image-ref: vecoli:latest
          format: sarif
          output: trivy-results.sarif
          vuln-type: os,library
          ignore-unfixed: true

      - name: Upload SARIF result
        id: upload-sarif
        if: github.event_name != 'pull_request'
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-results.sarif

      - name: Scan image with Trivy (JUnit)
        id: trivy-junit
        # Pinned to avoid template path bug in >0.34.0: https://github.com/aquasecurity/trivy-action/issues/509
        uses: aquasecurity/trivy-action@0.34.0
        with:
          image-ref: vecoli:latest
          format: template
          template: "@$HOME/.local/bin/trivy-bin/contrib/junit.tpl"
          output: trivy-junit.xml
          vuln-type: os,library
          ignore-unfixed: true

      - name: Publish Trivy test report (JUnit)
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: trivy-junit.xml
          summary-report: false
          failed-report: true
          pull-request: false
          github-report: false
          integrations-config: |
            {
              "junit-to-ctrf": {
                "enabled": true,
                "action": "convert",
                "options": {
                  "output": "./ctrf-reports/ctrf-report.json",
                  "toolname": "junit-to-ctrf",
                  "useSuiteName": false,
                  "env": {
                    "appName": "vEcoli"
                  }
                }
              }
            }
